### ISSUE TITLE
how to pass setup.py arguments

### ISSUE THREAD

**Issue by nekopsykose** [projg2/gpep517#10]
some projects have something like:

```
python3 setup.py build --system-lib-1
```

it's not clear how to pass the same kind of thing when just calling gpep517 build-wheel (setuptools backend). --config-json seems related, but it's not clear what corresponds to what exactly

**Comment by mgorny** [comment]
I'm sorry, I've missed this bug report.

It's basically `--config_json '{"--build-option": ["--foo1", "--foo2"]}'`. That said, setuptools supports only passing global options and not specific arguments to commands, at least not without hacks.

https://github.com/pypa/setuptools/issues/3896 is the upstream bug for documenting this.

**Comment by mgorny** [comment]
(we usually ask upstreams to make configuration via envvars possible)

**Comment by nekopsykose** [comment]
thanks!
