### ISSUE TITLE
Create wheel_dir automatically

### ISSUE THREAD

**Issue by ptrcnull** [projg2/gpep517#3]
while some build backends create the directory by themselves, some don't, but try to write to it anyway; gpep517 _could_ ensure that the wheel output directory exists and is a directory

**Comment by mgorny** [comment]
Sure, should be done now.

**Comment by mgorny** [comment]
Do you need me to make a new release for this?

**Comment by ptrcnull** [comment]
sorry, forgot to respond; it's not really necessary, but if you don't mind, that would be nice

**Comment by nekopsykose** [comment]
i had already backported the change for alpine packaging, so it's not necessary. thanks for the fantastic tool!

**Comment by mgorny** [comment]
Thanks. I suppose I'm not planning any other changes right now, so I'll just make a release.
