### ISSUE TITLE
Package tests fail when using `DISTUTILS_USE_PEP517=setuptools`

### ISSUE THREAD

**Issue by TheChymera** [projg2/gpep517#5]
I get the following error when trying to update [`=dev-python/traits-6.4.1::science`](https://gitweb.gentoo.org/proj/sci.git/tree/dev-python/traits/traits-6.4.1.ebuild) to use `DISTUTILS_USE_PEP517=setuptools`:

https://ppb.chymera.eu/56ce49.log

Any idea what the issue is?

**Comment by mgorny** [comment]
You're trying to use a directory that doesn't exist. Also, this has nothing to do with gpep517.
