### ISSUE TITLE
build-backend should fallback to setuptools.build_meta:__legacy__

### ISSUE THREAD

**Issue by sim6** [projg2/gpep517#8]
Firstly thanks for your work.

As described in

https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#fallback-behaviour

the `build-backend` should fallback to `setuptools.build_meta:__legacy__`

See also https://bugs.gentoo.org/905229 and https://gitlab.com/mkdocs-i18n/mkdocs-i18n/-/merge_requests/16

**Comment by mgorny** [comment]
It does: https://github.com/projg2/gpep517/blob/master/gpep517/__main__.py#L163

**Comment by sim6** [comment]
Sorry, I mean with `get-backend` that is used here https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/distutils-r1.eclass#n1196
